[package]
name = "tenx_technical_exercise"
version = "0.1.0"
authors = ["nyinyithann <nyinyithann@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
colored = "1.7.0"
quick-error = "1.2.2"